---
title: "vaccine_data"
author: "George WIlloughby"
date: "14/06/2021"
output: html_document
---
```{r}
library(httr)
library(jsonlite)
library(dplyr)
```

# Getting the vaccine data

```{r}
#' Extracts paginated data by requesting all of the pages
#' and combining the results.
#'
#' @param filters    API filters. See the API documentations for 
#'                   additional information.
#'                   
#' @param structure  Structure parameter. See the API documentations 
#'                   for additional information.
#'                   
#' @return list      Comprehensive list of dictionaries containing all 
#'                   the data for the given ``filter`` and ``structure`.`
get_paginated_data <- function (filters, structure) {
  
    endpoint     <- "https://api.coronavirus.data.gov.uk/v1/data"
    results      <- list()
    current_page <- 1
    
    repeat {

        httr::GET(
            url   = endpoint,
            query = list(
                filters   = paste(filters, collapse = ";"),
                structure = jsonlite::toJSON(structure, auto_unbox = TRUE),
                page      = current_page
            ),
            timeout(10)
        ) -> response
        
        # Handle errors:
        if ( response$status_code >= 400 ) {
            err_msg = httr::http_status(response)
            stop(err_msg)
        } else if ( response$status_code == 204 ) {
            break
        }
        
        # Convert response from binary to JSON:
        json_text <- content(response, "text")
        dt        <- jsonlite::fromJSON(json_text)
        results   <- rbind(results, dt$data)
        
        if ( is.null( dt$pagination$`next` ) ){
            break
        }
        
        current_page <- current_page + 1;

    }
    
    return(results)
    
}


# Create filters:
query_filters <- c(
    "areaType=overview"
)

# Create the structure as a list or a list of lists:
query_structure <- list(
    date       = "date", 
    name = "areaName",
    daily      = "newPeopleVaccinatedSecondDoseByPublishDate",
    cumulative = "cumPeopleVaccinatedSecondDoseByPublishDate"
)

latest_cumulative_second_dose <- get_paginated_data(query_filters, query_structure)

list(
  "Shape"                = dim(latest_cumulative_second_dose),
  "Data (first 3 items)" = latest_cumulative_second_dose[0:3, 0:-1]
) -> report

print(report)
```

# View the downloaded data

```{r}
latest_cumulative_second_dose
```

# Renaming columns for clarity

```{r}
library(dplyr)

latest_cumulative_second_dose <- latest_cumulative_second_dose %>%
  rename(
    cumulative_second_dose = cumulative,
    new_people_given_second_dose = daily
  )

latest_cumulative_second_dose
```

# Export the data

```{r}
write.csv(latest_cumulative_second_dose, "second-dose-cumulative.csv")
```








